# Ottergrad user guide


# Step 0
import Tensor and Func class
We also need import otternumpy and Sigmoid function as our example

In [13]:
import numpy as np
from Ottergrad.autograd import Tensor, Func
import Ottergrad.otternumpy as otnp
from Ottergrad.activation import Sigmoid

# Step 1
Create two Tensor type variable 'x' and 'y' from NumPy
We also create W which has no data for now

In [14]:
W = Tensor(np.ones((1,5)))
x = Tensor(np.ones((5,3)))


# Step 2
Let our first func be like:

In [15]:
func = Sigmoid(otnp.dot(W, x))
func = Func(func)

Notice that 'func' is typical linear layer type in neuron network

# Step 3
Let func do forward propagation once

In [16]:
func.forward()

array([[0.99330715, 0.99330715, 0.99330715]])

# Step 4
Computing the derivatives with the help of computation graph

In [17]:
func.backward()
W.getgrad()

array([[0.02035004, 0.02035004, 0.02035004, 0.02035004, 0.02035004]])

Another sample with using 'where'  function

In [18]:
a = Tensor()
a.setdata(np.array([[1, 2, 3], [4, 5, 6]]))
func = Func(otnp.where(a > 3, 3 * a, 0))
func.forward()
func.backward()
a.getgrad()

[[False False False]
 [ True  True  True]]


array([[1., 1., 1.],
       [3., 3., 3.]])