# Ottergrad user guide

Ottergrad is an automatic differentiation tool support plenty of NumPy functions who borns from Nuwa framework. This project separates the auto-derivative function from Nuwa into a package, whose algorithm is more efficient, simpler and more stable than Nuwa 0.0.2.

Edited by Zixing QIU (zixing.qiu@etu.toulouse-inp.fr)

# Step 0
import Tensor and Func class
We also need import otternumpy and Sigmoid function as our example

In [50]:
# ! sudo pip install -i https://test.pypi.org/simple/ Ottergrad
import numpy as np
from Ottergrad.autograd import Tensor, Func
import Ottergrad.otternumpy as otnp
from Ottergrad.activation import Sigmoid

# Step 1
Create two Tensor type variable 'x' and 'y' from NumPy
We also create W which has no data for now

In [51]:
W = Tensor(np.ones((1,5)))
x = Tensor(np.ones((5,3)))

# Step 2
Let our first func be like:

In [52]:
func = Sigmoid(otnp.dot(W, x))
func = Func(func)

Notice that 'func' is typical linear layer type in neuron network

# Step 3
Let func do forward propagation once

In [53]:
func.forward()

array([[0.99330715, 0.99330715, 0.99330715]])

# Step 4
Computing the derivatives with the help of computation graph

In [54]:
func.backward()
W.getgrad()

array([[0.02035004, 0.02035004, 0.02035004, 0.02035004, 0.02035004]])

Another sample with using 'where'  function

In [55]:
a = Tensor()
a.setdata(np.array([[1, 2, 3], [4, 5, 6]]))
func = Func(otnp.where(a > 3, 3 * a, 0))
func.forward()
func.backward()
a.getgrad()

array([[1., 1., 1.],
       [3., 3., 3.]])

Finally, we give a vivid 3 layers fully connected network to see if the gradient can be correctly given

In [56]:
x = Tensor(np.random.rand(5000, 30))
W1 = Tensor(np.random.rand(30,100))
W2 = Tensor(np.random.rand(100, 50))
W3 = Tensor(np.random.rand(50, 30))

l1 = Sigmoid(otnp.dot(x, W1))
l2 = Sigmoid(otnp.dot(l1, W2))
l3 = otnp.dot(l2, W3)
func = Func(l3)

func.forward()
func.backward()

print("W1's gradient is " + str(W1.getgrad()))

W1's gradient is [[1.55841779 3.09941541 2.56407321 ... 4.21642738 2.98262384 2.19862303]
 [1.49618532 3.07101007 2.50246591 ... 3.72816309 3.44169822 2.14018203]
 [1.57303764 2.91315111 2.5995923  ... 4.00325851 3.29807133 2.03043232]
 ...
 [1.4124521  3.21118696 2.62250154 ... 3.68704166 3.28038238 1.98191629]
 [1.5642053  2.93563087 2.7684254  ... 3.71760803 3.13955798 2.06892669]
 [1.42228891 3.08226813 2.89191136 ... 3.50635962 3.0772686  1.92641901]]
