# Ottergrad user guide
By Zixing QIU

# Step 0
import Tensor and Func class
We also need import otternumpy and Sigmoid function as our example

In [13]:
! sudo pip install -i https://test.pypi.org/simple/ Ottergrad
import numpy as np
from Ottergrad.autograd import Tensor, Func
import Ottergrad.otternumpy as otnp
from Ottergrad.activation import Sigmoid

# Step 1
Create two Tensor type variable 'x' and 'y' from NumPy
We also create W which has no data for now

In [14]:
W = Tensor(np.ones((1,5)))
x = Tensor(np.ones((5,3)))

# Step 2
Let our first func be like:

In [15]:
func = Sigmoid(otnp.dot(W, x))
func = Func(func)

Notice that 'func' is typical linear layer type in neuron network

# Step 3
Let func do forward propagation once

In [16]:
func.forward()

array([[0.99330715, 0.99330715, 0.99330715]])

# Step 4
Computing the derivatives with the help of computation graph

In [17]:
func.backward()
W.getgrad()

array([[0.02035004, 0.02035004, 0.02035004, 0.02035004, 0.02035004]])

Another sample with using 'where'  function

In [18]:
a = Tensor()
a.setdata(np.array([[1, 2, 3], [4, 5, 6]]))
func = Func(otnp.where(a > 3, 3 * a, 0))
func.forward()
func.backward()
a.getgrad()

array([[1., 1., 1.],
       [3., 3., 3.]])

Finally, we give a vivid 3 layers fully connected network to see if the gradient can be correctly given

In [ ]:
W1 = Tensor(np.ones((1,5)))
W2 = Tensor(np.ones((5,1)))
W3 = Tensor(np.ones((2, 5)))
x = Tensor(np.ones((5,3)))

l1 = Sigmoid(otnp.dot(W1, x))
l2 = Sigmoid(otnp.dot(W2, l1))
l3 = otnp.dot(W3, l2)
func = Func(l3)

func.forward()
func.backward()

print(W1.getgrad())